# Generated by Django 5.2.13 on 2026-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_syllabus_is_processed_syllabus_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
