# Generated by Django 5.2.13 on 2026-04-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
